Refactor pre_commit script
Co-authored-by: Gerhard Lazu <glazu@pivotal.io>

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,35 +1,61 @@
 #!/bin/sh
 
-LATEST_GO_VERSION="1.11"
-GO_VERSION="$(go version)"
+LATEST_STABLE_SUPPORTED_GO_VERSION="1.11"
 
-if [[ $GO_VERSION = *$LATEST_GO_VERSION* ]]; then
-  echo "Detected latest version of go... checking gofmt, golint and got vet"
+main() {
+  if local_go_version_is_latest_stable
+  then
+    run_gofmt
+    run_golint
+    run_govet
+  fi
+  run_unit_tests
+}
+
+local_go_version_is_latest_stable() {
+  go version | grep -q $LATEST_STABLE_SUPPORTED_GO_VERSION
+}
+
+error() {
+  echo "$*" 1>&2
+}
+
+run_gofmt() {
+  error "Detected latest version of go... checking gofmt, golint and got vet"
   GOFMT_FILES=$(gofmt -l .)
-  if [ -n "${GOFMT_FILES}" ]; then
-    printf >&2 'gofmt failed for the following files:\n%s\n\nplease run "gofmt -w ." on your changes before committing.\n' "${GOFMT_FILES}"
+  if [ -n "$GOFMT_FILES" ]; then
+    error "gofmt failed for the following files:
+$GOFMT_FILES
+please run 'gofmt -w .' on your changes before committing."
     exit 1
   fi
+}
 
+run_golint() {
   GOLINT_ERRORS=$(golint ./... | grep -v "Id should be")
-  if [ -n "${GOLINT_ERRORS}" ]; then
-    printf >&2 'golint failed for the following reasons:\n%s\n\nplease run 'golint ./...' on your changes before committing.\n' "${GOLINT_ERRORS}"
+  if [ -n "$GOLINT_ERRORS" ]; then
+    error "golint failed for the following reasons:
+$GOLINT_ERRORS
+please run 'golint ./...' on your changes before committing."
     exit 1
   fi
+}
 
-  GOVET_ERRORS=$(go tool vet *.go 2>&1)
-  if [ -n "${GOVET_ERRORS}" ]; then
-    printf >&2 'go vet failed for the following reasons:\n%s\n\nplease run "go tool vet *.go" on your changes before committing.\n' "${GOVET_ERRORS}"
+run_govet() {
+  GOVET_ERRORS=$(go tool vet ./*.go 2>&1)
+  if [ -n "$GOVET_ERRORS" ]; then
+    error "go vet failed for the following reasons:
+$GOVET_ERRORS
+please run 'go tool vet ./*.go' on your changes before committing."
     exit 1
   fi
-fi
+}
 
-if [ -z "${NOTEST}" ]; then
-  printf >&2 'Running short tests...\n'
-  env AMQP_URL= go test -short -v | egrep 'PASS|ok'
-
-  if [ $? -ne 0 ]; then
-    printf >&2 'go test failed, please fix before committing.\n'
-    exit 1
+run_unit_tests() {
+  if [ -z "$NOTEST" ]; then
+    error 'Running short tests...'
+    env AMQP_URL= go test -short
   fi
-fi
+}
+
+main
