Run golint and go vet in pre-commit
In order to support more contributors, make sure the code passes basic
Go lint and vet rules.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,7 +1,29 @@
 #!/bin/sh
 
+GOFMT_FILES=$(gofmt -l .)
+if [ -n "${GOFMT_FILES}" ]; then
+  printf >&2 'gofmt failed for the following files:\n%s\n\nplease run "gofmt -w ." on your changes before committing.\n' "${GOFMT_FILES}"
+  exit 1
+fi
 
-gofmt -l . | egrep . && echo "^^^ go fmt" && exit 1
+GOLINT_ERRORS=$(golint ./... | grep -v "Id should be")
+if [ -n "${GOLINT_ERRORS}" ]; then
+  printf >&2 'golint failed for the following reasons:\n%s\n\nplease run 'golint ./...' on your changes before committing.\n' "${GOLINT_ERRORS}"
+  exit 1
+fi
 
+GOVET_ERRORS=$(go tool vet -copylocks=false .)
+if [ -n "${GOVET_ERRORS}" ]; then
+  printf >&2 'go vet failed for the following reasons:\n%s\n\nplease run 'go tool vet .' on your changes before committing.\n' "${GOVET_ERRORS}"
+  exit 1
+fi
 
-[ ! -z $NOTEST ] || exec env AMQP_URL= go test
+if [ -z "${NOTEST}" ]; then
+  printf >&2 'Running short tests...\n'
+  env AMQP_URL= go test -short -v | egrep 'PASS|ok'
+
+  if [ $? -ne 0 ]; then
+    printf >&2 'go test failed, please fix before committing.\n'
+    exit 1
+  fi
+fi
