Fail pre-commit on `go vet`

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -12,9 +12,9 @@ if [ -n "${GOLINT_ERRORS}" ]; then
   exit 1
 fi
 
-GOVET_ERRORS=$(go tool vet -copylocks=false .)
+GOVET_ERRORS=$(go tool vet -copylocks=false *.go 2>&1)
 if [ -n "${GOVET_ERRORS}" ]; then
-  printf >&2 'go vet failed for the following reasons:\n%s\n\nplease run 'go tool vet .' on your changes before committing.\n' "${GOVET_ERRORS}"
+  printf >&2 'go vet failed for the following reasons:\n%s\n\nplease run "go tool vet *.go" on your changes before committing.\n' "${GOVET_ERRORS}"
   exit 1
 fi
 
