Run gofmt, golint, and govet only with latest go
In some cases these tools output differently. If they do, we just care about
the last version of go.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,21 +1,27 @@
 #!/bin/sh
 
-GOFMT_FILES=$(gofmt -l .)
-if [ -n "${GOFMT_FILES}" ]; then
-  printf >&2 'gofmt failed for the following files:\n%s\n\nplease run "gofmt -w ." on your changes before committing.\n' "${GOFMT_FILES}"
-  exit 1
-fi
+LATEST_GO_VERSION="1.11"
+GO_VERSION="$(go version)"
 
-GOLINT_ERRORS=$(golint ./... | grep -v "Id should be")
-if [ -n "${GOLINT_ERRORS}" ]; then
-  printf >&2 'golint failed for the following reasons:\n%s\n\nplease run 'golint ./...' on your changes before committing.\n' "${GOLINT_ERRORS}"
-  exit 1
-fi
+if [[ $GO_VERSION = *$LATEST_GO_VERSION* ]]; then
+  echo "Detected latest version of go... checking gofmt, golint and got vet"
+  GOFMT_FILES=$(gofmt -l .)
+  if [ -n "${GOFMT_FILES}" ]; then
+    printf >&2 'gofmt failed for the following files:\n%s\n\nplease run "gofmt -w ." on your changes before committing.\n' "${GOFMT_FILES}"
+    exit 1
+  fi
 
-GOVET_ERRORS=$(go tool vet *.go 2>&1)
-if [ -n "${GOVET_ERRORS}" ]; then
-  printf >&2 'go vet failed for the following reasons:\n%s\n\nplease run "go tool vet *.go" on your changes before committing.\n' "${GOVET_ERRORS}"
-  exit 1
+  GOLINT_ERRORS=$(golint ./... | grep -v "Id should be")
+  if [ -n "${GOLINT_ERRORS}" ]; then
+    printf >&2 'golint failed for the following reasons:\n%s\n\nplease run 'golint ./...' on your changes before committing.\n' "${GOLINT_ERRORS}"
+    exit 1
+  fi
+
+  GOVET_ERRORS=$(go tool vet *.go 2>&1)
+  if [ -n "${GOVET_ERRORS}" ]; then
+    printf >&2 'go vet failed for the following reasons:\n%s\n\nplease run "go tool vet *.go" on your changes before committing.\n' "${GOVET_ERRORS}"
+    exit 1
+  fi
 fi
 
 if [ -z "${NOTEST}" ]; then
